Display fail message

diff --git a/scripts/nscripts/deployallosb b/scripts/nscripts/deployallosb
--- a/scripts/nscripts/deployallosb
+++ b/scripts/nscripts/deployallosb
@@ -1,8 +1,9 @@
 #!/bin/bash
 
 PROJECT=`printf '%q\n' "${PWD##*/}"`
-GREEN='\033[1;32m'
 CLEAR='\033[0m'
+GREEN='\033[1;32m'
+RED='\033[0;31m'
 
 if [[ ! $PROJECT = osb-* ]]; then
     echo "Please execute from a liferay OSB- project"; return "1";
@@ -16,7 +17,7 @@ deployAll() {
         if [[ ! "." = $dir ]]; then
             cd $dir 
             echo -e "\n${GREEN}CD to $dir${CLEAR}\n"
-            rungradle clean deploy
+            rungradle clean deploy || echo -e "${RED}ERROR: gradle clean deploy failed.${CLEAR}"
             cd $SRC_DIR;
         fi
     done
